apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/pipeline-tutorial-189721/pipeline:6e8fa37b2a6c24b9024db7c2a976ceffea1e433f
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
